name: Issue Moderation

on:
  issues:
    types: [opened]

jobs:
  close_non_member_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Close issue if not opened by repo members
        uses: actions/github-script@v7
        with:
          script: |
            // Get the permission level of the issue author
            const { data: perm } = await github.rest.repos.getCollaboratorPermissionLevel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              username: context.payload.issue.user.login
            });
            const allowedPermissions = ['admin', 'maintain', 'write'];
            if (!allowedPermissions.includes(perm.permission)) {
              // Add comment
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.issue.number,
                body: "Thanks for your input, but only working group members can participate in this repository."
              });
              // Close issue
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.issue.number,
                state: "closed"
              });
            }
      - name: Lock issue
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.lock({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              lock_reason: "resolved"
            });
